// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: star.proto

package starclient

import (
	"context"

	"ymir.com/app/star/rpc/star"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	StarDetailRequest    = star.StarDetailRequest
	StarDetailResponse   = star.StarDetailResponse
	StarListRequest      = star.StarListRequest
	StarListResponse     = star.StarListResponse
	StarListResponseItem = star.StarListResponseItem

	Star interface {
		StarList(ctx context.Context, in *StarListRequest, opts ...grpc.CallOption) (*StarListResponse, error)
		StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error)
	}

	defaultStar struct {
		cli zrpc.Client
	}
)

func NewStar(cli zrpc.Client) Star {
	return &defaultStar{
		cli: cli,
	}
}

func (m *defaultStar) StarList(ctx context.Context, in *StarListRequest, opts ...grpc.CallOption) (*StarListResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.StarList(ctx, in, opts...)
}

func (m *defaultStar) StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.StarDetail(ctx, in, opts...)
}
