// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: product.proto

package server

import (
	"context"

	"ymir.com/app/product/rpc/internal/logic"
	"ymir.com/app/product/rpc/internal/svc"
	"ymir.com/app/product/rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) ProductList(ctx context.Context, in *product.ProductListRequest) (*product.ProductListResponse, error) {
	l := logic.NewProductListLogic(ctx, s.svcCtx)
	return l.ProductList(in)
}

func (s *ProductServer) ProductDetail(ctx context.Context, in *product.ProductDetailReqeust) (*product.ProductDetailResponse, error) {
	l := logic.NewProductDetailLogic(ctx, s.svcCtx)
	return l.ProductDetail(in)
}
