// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: productadmin.proto

package productclient

import (
	"context"

	"ymir.com/app/product/admin/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ProductCountRequest  = product.ProductCountRequest
	ProductCountResponse = product.ProductCountResponse

	Product interface {
		ProductCount(ctx context.Context, in *ProductCountRequest, opts ...grpc.CallOption) (*ProductCountResponse, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) ProductCount(ctx context.Context, in *ProductCountRequest, opts ...grpc.CallOption) (*ProductCountResponse, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ProductCount(ctx, in, opts...)
}
