// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: star.proto

package server

import (
	"context"

	"ymir.com/app/star/rpc/internal/logic"
	"ymir.com/app/star/rpc/internal/svc"
	"ymir.com/app/star/rpc/star"
)

type StarServer struct {
	svcCtx *svc.ServiceContext
	star.UnimplementedStarServer
}

func NewStarServer(svcCtx *svc.ServiceContext) *StarServer {
	return &StarServer{
		svcCtx: svcCtx,
	}
}

func (s *StarServer) StarList(ctx context.Context, in *star.StarListRequest) (*star.StarListResponse, error) {
	l := logic.NewStarListLogic(ctx, s.svcCtx)
	return l.StarList(in)
}

func (s *StarServer) StarDetail(ctx context.Context, in *star.StarDetailRequest) (*star.StarDetailResponse, error) {
	l := logic.NewStarDetailLogic(ctx, s.svcCtx)
	return l.StarDetail(in)
}
