// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: useradmin.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrganizerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      *int64  `protobuf:"varint,1,opt,name=UserId,proto3,oneof" json:"UserId,omitempty"`
	Phonenumber *string `protobuf:"bytes,3,opt,name=Phonenumber,proto3,oneof" json:"Phonenumber,omitempty"`
}

func (x *GetOrganizerRequest) Reset() {
	*x = GetOrganizerRequest{}
	mi := &file_useradmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerRequest) ProtoMessage() {}

func (x *GetOrganizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_useradmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizerRequest) Descriptor() ([]byte, []int) {
	return file_useradmin_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrganizerRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetOrganizerRequest) GetPhonenumber() string {
	if x != nil && x.Phonenumber != nil {
		return *x.Phonenumber
	}
	return ""
}

type Organizer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Phonenumber string `protobuf:"bytes,3,opt,name=Phonenumber,proto3" json:"Phonenumber,omitempty"`
	Role        int64  `protobuf:"varint,4,opt,name=Role,proto3" json:"Role,omitempty"`
}

func (x *Organizer) Reset() {
	*x = Organizer{}
	mi := &file_useradmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organizer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organizer) ProtoMessage() {}

func (x *Organizer) ProtoReflect() protoreflect.Message {
	mi := &file_useradmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organizer.ProtoReflect.Descriptor instead.
func (*Organizer) Descriptor() ([]byte, []int) {
	return file_useradmin_proto_rawDescGZIP(), []int{1}
}

func (x *Organizer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organizer) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *Organizer) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

type GetOrganizerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Organizer *Organizer `protobuf:"bytes,1,opt,name=organizer,proto3" json:"organizer,omitempty"`
}

func (x *GetOrganizerResponse) Reset() {
	*x = GetOrganizerResponse{}
	mi := &file_useradmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerResponse) ProtoMessage() {}

func (x *GetOrganizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_useradmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizerResponse) Descriptor() ([]byte, []int) {
	return file_useradmin_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrganizerResponse) GetOrganizer() *Organizer {
	if x != nil {
		return x.Organizer
	}
	return nil
}

var File_useradmin_proto protoreflect.FileDescriptor

var file_useradmin_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x74, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x00, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b,
	0x50, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0e,
	0x0a, 0x0c, 0x5f, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x51,
	0x0a, 0x09, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x52, 0x6f, 0x6c,
	0x65, 0x22, 0x46, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x09,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x32, 0x4f, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65,
	0x72, 0x12, 0x1a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_useradmin_proto_rawDescOnce sync.Once
	file_useradmin_proto_rawDescData = file_useradmin_proto_rawDesc
)

func file_useradmin_proto_rawDescGZIP() []byte {
	file_useradmin_proto_rawDescOnce.Do(func() {
		file_useradmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_useradmin_proto_rawDescData)
	})
	return file_useradmin_proto_rawDescData
}

var file_useradmin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_useradmin_proto_goTypes = []any{
	(*GetOrganizerRequest)(nil),  // 0: admin.GetOrganizerRequest
	(*Organizer)(nil),            // 1: admin.Organizer
	(*GetOrganizerResponse)(nil), // 2: admin.GetOrganizerResponse
}
var file_useradmin_proto_depIdxs = []int32{
	1, // 0: admin.GetOrganizerResponse.organizer:type_name -> admin.Organizer
	0, // 1: admin.user.GetOrganizer:input_type -> admin.GetOrganizerRequest
	2, // 2: admin.user.GetOrganizer:output_type -> admin.GetOrganizerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_useradmin_proto_init() }
func file_useradmin_proto_init() {
	if File_useradmin_proto != nil {
		return
	}
	file_useradmin_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_useradmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_useradmin_proto_goTypes,
		DependencyIndexes: file_useradmin_proto_depIdxs,
		MessageInfos:      file_useradmin_proto_msgTypes,
	}.Build()
	File_useradmin_proto = out.File
	file_useradmin_proto_rawDesc = nil
	file_useradmin_proto_goTypes = nil
	file_useradmin_proto_depIdxs = nil
}
