// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package userclient

import (
	"context"

	"ymir.com/app/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetCaptchaRequest                    = user.GetCaptchaRequest
	GetCaptchaResponse                   = user.GetCaptchaResponse
	GetUserRequest                       = user.GetUserRequest
	GetUserResponse                      = user.GetUserResponse
	SendCaptchaToEmailRequest            = user.SendCaptchaToEmailRequest
	SendCaptchaToEmailResponse           = user.SendCaptchaToEmailResponse
	SendCaptchaToPhonenumberRequest      = user.SendCaptchaToPhonenumberRequest
	SendPhonenumberResponse              = user.SendPhonenumberResponse
	UserInfo                             = user.UserInfo
	WriteUserInDBWithEmailRequest        = user.WriteUserInDBWithEmailRequest
	WriteUserInDBWithEmailResponse       = user.WriteUserInDBWithEmailResponse
	WriteUserInDBWithPhonenumberRequest  = user.WriteUserInDBWithPhonenumberRequest
	WriteUserInDBWithPhonenumberResponse = user.WriteUserInDBWithPhonenumberResponse

	User interface {
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		SendCaptchaToEmail(ctx context.Context, in *SendCaptchaToEmailRequest, opts ...grpc.CallOption) (*SendCaptchaToEmailResponse, error)
		SendCaptchaToPhonenumber(ctx context.Context, in *SendCaptchaToPhonenumberRequest, opts ...grpc.CallOption) (*SendPhonenumberResponse, error)
		GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error)
		WriteUserInDBWithEmail(ctx context.Context, in *WriteUserInDBWithEmailRequest, opts ...grpc.CallOption) (*WriteUserInDBWithEmailResponse, error)
		WriteUserInDBWithPhonenumber(ctx context.Context, in *WriteUserInDBWithPhonenumberRequest, opts ...grpc.CallOption) (*WriteUserInDBWithPhonenumberResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) SendCaptchaToEmail(ctx context.Context, in *SendCaptchaToEmailRequest, opts ...grpc.CallOption) (*SendCaptchaToEmailResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendCaptchaToEmail(ctx, in, opts...)
}

func (m *defaultUser) SendCaptchaToPhonenumber(ctx context.Context, in *SendCaptchaToPhonenumberRequest, opts ...grpc.CallOption) (*SendPhonenumberResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendCaptchaToPhonenumber(ctx, in, opts...)
}

func (m *defaultUser) GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetCaptcha(ctx, in, opts...)
}

func (m *defaultUser) WriteUserInDBWithEmail(ctx context.Context, in *WriteUserInDBWithEmailRequest, opts ...grpc.CallOption) (*WriteUserInDBWithEmailResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.WriteUserInDBWithEmail(ctx, in, opts...)
}

func (m *defaultUser) WriteUserInDBWithPhonenumber(ctx context.Context, in *WriteUserInDBWithPhonenumberRequest, opts ...grpc.CallOption) (*WriteUserInDBWithPhonenumberResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.WriteUserInDBWithPhonenumber(ctx, in, opts...)
}
