// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package server

import (
	"context"

	"ymir.com/app/user/rpc/internal/logic"
	"ymir.com/app/user/rpc/internal/svc"
	"ymir.com/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) SendCaptchaToEmail(ctx context.Context, in *user.SendCaptchaToEmailRequest) (*user.SendCaptchaToEmailResponse, error) {
	l := logic.NewSendCaptchaToEmailLogic(ctx, s.svcCtx)
	return l.SendCaptchaToEmail(in)
}

func (s *UserServer) GetCaptchaByEmail(ctx context.Context, in *user.GetCaptchaByEmailRequest) (*user.GetCaptchaResponse, error) {
	l := logic.NewGetCaptchaByEmailLogic(ctx, s.svcCtx)
	return l.GetCaptchaByEmail(in)
}

func (s *UserServer) GetCaptchaByPhonenumber(ctx context.Context, in *user.GetCaptchaByPhonenumberRequest) (*user.GetCaptchaResponse, error) {
	l := logic.NewGetCaptchaByPhonenumberLogic(ctx, s.svcCtx)
	return l.GetCaptchaByPhonenumber(in)
}

func (s *UserServer) WriteUserInDBWithEmail(ctx context.Context, in *user.WriteUserInDBWithEmailRequest) (*user.WriteUserInDBWithEmailResponse, error) {
	l := logic.NewWriteUserInDBWithEmailLogic(ctx, s.svcCtx)
	return l.WriteUserInDBWithEmail(in)
}

func (s *UserServer) WriteUserInDBWithPhonenumber(ctx context.Context, in *user.WriteUserInDBWithPhonenumberRequest) (*user.WriteUserInDBWithPhonenumberResponse, error) {
	l := logic.NewWriteUserInDBWithPhonenumberLogic(ctx, s.svcCtx)
	return l.WriteUserInDBWithPhonenumber(in)
}
