// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	star "ymir.com/app/bffs/internal/handler/star"
	"ymir.com/app/bffs/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/star/list",
					Handler: star.StarListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/internal"),
	)
}
