// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	auth "ymir.com/app/bffs/internal/handler/auth"
	star "ymir.com/app/bffs/internal/handler/star"
	"ymir.com/app/bffs/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/signin",
				Handler: auth.SigninHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/internal"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/star/:id",
					Handler: star.StarDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/star/:id/update",
					Handler: star.UpdateStarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/star/create",
					Handler: star.CreateStarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/star/list",
					Handler: star.StarListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/internal"),
	)
}
