// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: staradmin.proto

package server

import (
	"context"

	"ymir.com/app/star/admin/internal/logic"
	"ymir.com/app/star/admin/internal/svc"
	"ymir.com/app/star/admin/star"
)

type StarServer struct {
	svcCtx *svc.ServiceContext
	star.UnimplementedStarServer
}

func NewStarServer(svcCtx *svc.ServiceContext) *StarServer {
	return &StarServer{
		svcCtx: svcCtx,
	}
}

func (s *StarServer) StarList(ctx context.Context, in *star.StarListRequest) (*star.StarListResponse, error) {
	l := logic.NewStarListLogic(ctx, s.svcCtx)
	return l.StarList(in)
}

func (s *StarServer) StarDetail(ctx context.Context, in *star.StarDetailRequest) (*star.StarDetailResponse, error) {
	l := logic.NewStarDetailLogic(ctx, s.svcCtx)
	return l.StarDetail(in)
}

func (s *StarServer) UpdateStar(ctx context.Context, in *star.UpdateStarReqeust) (*star.UpdateStarResponse, error) {
	l := logic.NewUpdateStarLogic(ctx, s.svcCtx)
	return l.UpdateStar(in)
}

func (s *StarServer) CreateStar(ctx context.Context, in *star.CreateStarRequest) (*star.CreateStarResponse, error) {
	l := logic.NewCreateStarLogic(ctx, s.svcCtx)
	return l.CreateStar(in)
}
