// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: productadmin.proto

package server

import (
	"context"

	"ymir.com/app/product/admin/internal/logic"
	"ymir.com/app/product/admin/internal/svc"
	"ymir.com/app/product/admin/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) ProductCount(ctx context.Context, in *product.ProductCountRequest) (*product.ProductCountResponse, error) {
	l := logic.NewProductCountLogic(ctx, s.svcCtx)
	return l.ProductCount(in)
}
