// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddProductAmountInCartRequest struct {
	ProductId      string `json:"product_id"`
	ColorId        string `json:"color_id"`
	Size           string `json:"size"`
	ExpectedAmount int64  `json:"expected_amount"`
}

type AddProductAmountInCartResponse struct {
	ProductCartId string `json:"product_cart_id"`
	Amount        int64  `json:"amount"`
	TotalPrice    int64  `json:"total_price"`
}

type AddProductToCartRequest struct {
	ProductId string `json:"product_id"`
	ColorId   string `json:"color_id"`
	Size      string `json:"size"`
}

type AddProductToCartResponse struct {
	ProductCartId string `json:"product_cart_id"`
}

type CapturePaypalOrderRequest struct {
	OrderId       string `json:"order_id"`
	PaypalOrderId string `json:"paypal_order_id"`
}

type CapturePaypalOrderResponse struct {
	OrderId   string    `json:"order_id"`
	Status    string    `json:"status"`
	PayerInfo PayerInfo `json:"payer_info"`
}

type CheckIfUserSignedUpRequest struct {
	Email       *string `json:"email,optional"`
	PhoneNumber *string `json:"phone_number,optional"`
}

type CheckIfUserSignedUpResponse struct {
	OK bool `json:"ok"`
}

type CreateOrderRequest struct {
	RequestId string      `json:"request_id"`
	Orders    []OrderItem `json:"orders"`
}

type CreateOrderResponse struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
}

type CreatePaypalOrderRequest struct {
	RequestId string `json:"request_id"`
	OrderId   string `json:"order_id"`
}

type CreatePaypalOrderResponse struct {
	OrderId       string `json:"order_id"`
	PaypalOrderId string `json:"paypal_order_id"`
}

type DecreaseProductAmountInCartRequest struct {
	ProductId string `json:"product_id"`
	ColorId   string `json:"color_id"`
	Size      string `json:"size"`
}

type DecreaseProductAmountInCartResponse struct {
	ProductCartId string `json:"product_cart_id"`
	Amount        int64  `json:"amount"`
	TotalPrice    int64  `json:"total_price"`
}

type DecreaseStockRequest struct {
	ProductStockId string `json:"product_stock_id"`
	Quantity       int64  `json:"quantity"`
}

type DecreaseStockResponse struct {
	ProductStockId string `json:"product_stock_id"`
	Quantity       int64  `json:"quantity"`
}

type DeleteORderResponse struct {
	OrderId string `json:"order_id"`
}

type DeleteOrderRequest struct {
	OrderId string `json:"order_id"`
}

type ForgetPasswordRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Password    string  `json:"password"`
}

type ForgetpasswordResponse struct {
	OK bool `json:"ok"`
}

type GetIpAddressRequest struct {
}

type GetIpAddressResponse struct {
	Ip string `json:"ip"`
}

type GetOrderAddressRequest struct {
	OrderId string `path:"orderId"`
}

type GetOrderAddressResponse struct {
	Address OrderAddress `json:"address"`
}

type GetOrderDetailRequest struct {
	OrderId string `path:"orderId"`
}

type GetOrderDetailResponse struct {
	Order      Order       `json:"order"`
	OrderItems []OrderItem `json:"order_items"`
}

type GetOrderItemRequest struct {
	OrderId string `path:"orderId"`
}

type GetOrderItemResponse struct {
	OrderItems []OrderItem `json:"order_items"`
	Total      int64       `json:"total"`
}

type GetOrderListRequest struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type GetOrderListResponse struct {
	Orders []OrderListItem `json:"orders"`
	Total  int64           `json:"total"`
}

type IncreaseStockRequest struct {
	PorudctStockId string `json:"product_stock_id"`
	Quantity       int64  `json:"quantity"`
}

type IncreaseStockResponse struct {
	ProductStockId string `json:"product_stock_id"`
	Quantity       int64  `json:"quantity"`
}

type LikeCommmentRequest struct {
	CommentId string `json:"comment_id"`
}

type Order struct {
	RequestId string `json:"request_id"`
	OrderId   string `json:"order_id"`
	Status    string `json:"status"`
	Price     int64  `json:"price"`
	Unit      string `json:"unit"`
}

type OrderAddress struct {
	AddressLine1 string `json:"address_line_1"`
	AddressLine2 string `json:"address_line_2"`
	AdminArea1   string `json:"admin_area_1"`
	AdminArea2   string `json:"admin_area_2"`
	PostalCode   string `json:"postal_code"`
	CountryCode  string `json:"country_code"`
	Email        string `json:"email"`
	FullName     string `json:"full_name"`
}

type OrderItem struct {
	ProductId          string `json:"product_id"`
	ProductDescription string `json:"product_description"`
	ProductCoverUrl    string `json:"product_cover_url"`
	ProductColorId     string `json:"product_color_id"`
	Color              string `json:"color"`
	Size               string `json:"size"`
	Quantity           int64  `json:"quantity"`
	Price              int64  `json:"price,optional"`
}

type OrderListItem struct {
	OrderId        string   `json:"order_id"`
	CreatedAt      int64    `json:"created_at"`
	CoverUrls      []string `json:"cover_urls"`
	Status         string   `json:"status"`
	Price          int64    `json:"price"`
	Unit           string   `json:"unit"`
	OrderItemTotal int64    `json:"order_item_total"`
}

type OssTokenRequest struct {
}

type OssTokenResponse struct {
	AccessKeyId     string `json:"access_key_id"`
	AccessKeySecret string `json:"access_key_secret"`
	Expiration      string `json:"expiration"`
	SecurityToken   string `json:"security_token"`
}

type PayerAddress struct {
	AddressLine1 string `json:"address_line_1"`
	AddressLine2 string `json:"address_line_2"`
	AdminArea1   string `json:"admin_area_1"`
	AdminArea2   string `json:"admin_area_2"`
	PostalCode   string `json:"postal_code"`
	CountryCode  string `json:"country_code"`
}

type PayerInfo struct {
	Email         string       `json:"email"`
	PayerFullName string       `json:"payer_full_name"`
	PayerAddress  PayerAddress `json:"payer_address"`
}

type PayerName struct {
	GivenName string `json:"given_name"`
	Surname   string `json:"surname"`
}

type PayerPhone struct {
	PhoneNumber string `json:"phone_number"`
	PhoneType   string `json:"phone_type"`
}

type ProductCartListItem struct {
	ProductCartId string `json:"product_cart_id"`
	ProductId     string `json:"product_id"`
	StarId        string `json:"star_id"`
	ColorId       string `json:"color_id"`
	Color         string `json:"color"`
	Description   string `json:"description"`
	Price         int64  `json:"price"`
	Unit          string `json:"unit"`
	CoverUrl      string `json:"cover_url"`
	Amount        int64  `json:"amount"`
	Size          string `json:"size"`
	TotalPrice    int64  `json:"total_price"`
	Stock         int64  `json:"stock"`
}

type ProductCartListRequest struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type ProductCartListResponse struct {
	Products []ProductCartListItem `json:"products"`
	Total    int64                 `json:"total"`
}

type ProductColor struct {
	Id           string        `json:"id"`
	ColorName    string        `json:"color_name"`
	Images       []string      `json:"images"`
	DetailImages []string      `json:"detail_images"`
	Price        int64         `json:"price"`
	CoverUrl     string        `json:"cover_url"`
	Unit         string        `json:"unit"`
	Size         []ProductSize `json:"size"`
	IsDefault    bool          `json:"is_default"`
}

type ProductColorListItem struct {
	ColorId  string `json:"color_id"`
	CoverUrl string `json:"cover_url"`
}

type ProductComment struct {
	Id          string   `json:"id"`
	UserName    string   `json:"user_name"`
	UserAvatar  string   `json:"user_avatar"`
	Rate        float64  `json:"rate"`
	Comment     string   `json:"comment"`
	LikeNum     int64    `json:"like_num"`
	Images      []string `json:"images"`
	ImagesThumb []string `json:"images_thumb"`
	CreatedAt   int64    `json:"created_at"`
	Size        string   `json:"size"`
	Color       string   `json:"color"`
}

type ProductCommentRequest struct {
	ProductId string `json:"product_id"`
	Page      int64  `json:"page"`
	PageSize  int64  `json:"page_size"`
}

type ProductCommentResponse struct {
	Comments []ProductComment `json:"comments"`
	Total    int64            `json:"total"`
}

type ProductDetailRequest struct {
	Id string `path:"productId"`
}

type ProductDetailResponse struct {
	Id          string                 `json:"id"`
	Description string                 `json:"description"`
	Rate        float64                `json:"rate"`
	RateCount   int64                  `json:"rate_count"`
	Colors      []ProductColor         `json:"colors"`
	SoldNum     int64                  `json:"sold_num"`
	Detail      *string                `json:"detail"`
	StarAvatar  string                 `json:"star_avatar"`
	StarName    string                 `json:"star_name"`
	StarId      string                 `json:"star_id"`
	StarRate    float64                `json:"star_rate"`
	Comments    ProductCommentResponse `json:"comments"`
}

type ProductListColorItem struct {
	CoverUrl string `json:"cover_url"`
	Price    int64  `json:"price"`
	Unit     string `json:"unit"`
}

type ProductListItem struct {
	Id           string               `json:"id"`
	Description  string               `json:"description"`
	DefaultColor ProductListColorItem `json:"default_color"`
}

type ProductListRequest struct {
	StarId   *string `form:"star_id,optional"`
	Keyword  *string `form:"keyword,optional"`
	Page     int64   `form:"page"`
	PageSize int64   `form:"page_size"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type ProductSize struct {
	SizeName string `json:"size_name"`
	InStock  int64  `json:"in_stock"`
}

type RecommendStarListItem struct {
	StarId     string `json:"star_id"`
	StarAvatar string `json:"star_avatar"`
	StarName   string `json:"star_name"`
}

type RecommendStarListRequest struct {
}

type RecommendStarListResponse struct {
	Recommends []RecommendStarListItem `json:"recommends"`
}

type RemoveProductFromCartRequest struct {
	ProductId string `json:"product_id"`
	ColorId   string `json:"color_id"`
}

type RemoveProductFromCartResponse struct {
}

type SendForgetPasswordCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendForgetPasswordCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SendSignupCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendSignupCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SigninRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SigninResponse struct {
	UserId      string `json:"user_id"`
	Username    string `json:"name"`
	AccessToken string `json:"access_token"`
	AvatarUrl   string `json:"avatar_url"`
}

type SigninWithGoogleRequest struct {
	Token string `json:"token"`
}

type SignupRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SignupResponse struct {
	UserId string `json:"user_id"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	CoverUrl string `json:"cover_url"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}

type UserDetailRequest struct {
}

type UserDetailResponse struct {
	Id          string  `json:"id"`
	Phonenumber *string `json:"phone_number"`
	Email       *string `json:"email"`
	Username    string  `json:"username"`
}

type VerifyCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Captcha     string  `json:"captcha"`
}

type VerifyCaptchaResponse struct {
	OK bool `json:"ok"`
}
