// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddProductAmountInCartRequest struct {
	ProductId string `json:"product_id"`
}

type AddProductAmountInCartResponse struct {
	OK bool `json:"ok"`
}

type ForgetPasswordRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Password    string  `json:"password"`
}

type ForgetpasswordResponse struct {
	OK bool `json:"ok"`
}

type GetIpAddressRequest struct {
}

type GetIpAddressResponse struct {
	Ip string `json:"ip"`
}

type ProductCartListItem struct {
	Id          string   `json:"id"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Unit        string   `json:"unit"`
	CoverUrl    string   `json:"cover_url"`
	Quantity    int64    `json:"quantity"`
	Sizes       []string `json:"sizes"`
}

type ProductCartListRequest struct {
}

type ProductCartListResponse struct {
	Products []ProductCartListItem `json:"product"`
}

type ProductDetailRequest struct {
	Id string `path:"productId"`
}

type ProductDetailResponse struct {
	Id           string         `json:"id"`
	Description  string         `json:"description"`
	Rate         float64        `json:"rate"`
	RateCount    int64          `json:"rate_count"`
	Price        float64        `json:"price"`
	Unit         string         `json:"unit"`
	Size         []string       `json:"size"`
	Color        string         `json:"color"`
	Images       []ProductImage `json:"images"`
	DetailImages []ProductImage `json:"detail_images"`
	SoldNum      int64          `json:"sold_num"`
	Detail       *string        `json:"detail"`
	StarAvatar   string         `json:"star_avatar"`
	StarName     string         `json:"star_name"`
	StarId       string         `json:"star_id"`
}

type ProductImage struct {
	Id  string `json:"id"`
	Url string `json:"url"`
}

type ProductListItem struct {
	Id          string  `json:"id"`
	CoverUrl    string  `json:"cover_url"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Unit        string  `json:"unit"`
}

type ProductListRequest struct {
	StarId   *string `json:"star_id,optional"`
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type RecommendStarListItem struct {
	StarId     string `json:"star_id"`
	StarAvatar string `json:"star_avatar"`
	StarName   string `json:"star_name"`
}

type RecommendStarListRequest struct {
}

type RecommendStarListResponse struct {
	Recommends []RecommendStarListItem `json:"recommends"`
}

type SendForgetPasswordCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendForgetPasswordCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SendSignupCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendSignupCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SigninRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SigninResponse struct {
	UserId      string `json:"user_id"`
	Username    string `json:"name"`
	AccessToken string `json:"access_token"`
	Role        int64  `json:"role"`
	AvatarUrl   string `json:"avatar_url"`
}

type SignupRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SignupResponse struct {
	UserId string `json:"user_id"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	CoverUrl string `json:"cover_url"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}

type UserDetailRequest struct {
}

type UserDetailResponse struct {
	Id          string  `json:"id"`
	Phonenumber *string `json:"phone_number"`
	Email       *string `json:"email"`
	Username    string  `json:"username"`
}

type VerifyCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Captcha     string  `json:"captcha"`
}

type VerifyCaptchaResponse struct {
	OK bool `json:"ok"`
}
