// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddProductAmountInCartRequest struct {
	ProductId string `json:"product_id"`
	Color     string `json:"color"`
}

type AddProductAmountInCartResponse struct {
}

type AddProductToCartRequest struct {
	ProductId string `json:"productId"`
	Color     string `json:"color"`
	Size      string `json:"size"`
}

type AddProductToCartResponse struct {
	ProductCartId string `json:"product_cart_id"`
}

type DecreaseProductAmountInCartRequest struct {
	ProductId string `json:"product_id"`
	Color     string `json:"color"`
}

type DecreaseProductAmountInCartResponse struct {
}

type ForgetPasswordRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Password    string  `json:"password"`
}

type ForgetpasswordResponse struct {
	OK bool `json:"ok"`
}

type GetIpAddressRequest struct {
}

type GetIpAddressResponse struct {
	Ip string `json:"ip"`
}

type ProductCartListItem struct {
	Id          string   `json:"id"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Unit        string   `json:"unit"`
	CoverUrl    string   `json:"cover_url"`
	Amount      int64    `json:"amount"`
	Sizes       []string `json:"sizes"`
}

type ProductCartListRequest struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type ProductCartListResponse struct {
	Products []ProductCartListItem `json:"product"`
	Total    int64                 `json:"total"`
}

type ProductColor struct {
	Id            string        `json:"id"`
	ColorName     string        `json:"color_name"`
	Images        []string      `json:"images"`
	Detail_Images []string      `json:"detail_images"`
	Price         float64       `json:"price"`
	Unit          string        `json:"unit"`
	Size          []ProductSize `json:"size"`
}

type ProductColorListItem struct {
	ColorId  string `json:"color_id"`
	CoverUrl string `json:"cover_url"`
}

type ProductDetailRequest struct {
	Id string `path:"productId"`
}

type ProductDetailResponse struct {
	Id          string                 `json:"id"`
	Description string                 `json:"description"`
	Rate        float64                `json:"rate"`
	RateCount   int64                  `json:"rate_count"`
	Color       ProductColor           `json:"color"`
	ColorList   []ProductColorListItem `json:"color_list"`
	SoldNum     int64                  `json:"sold_num"`
	Detail      *string                `json:"detail"`
	StarAvatar  string                 `json:"star_avatar"`
	StarName    string                 `json:"star_name"`
	StarId      string                 `json:"star_id"`
}

type ProductListItem struct {
	Id          string  `json:"id"`
	CoverUrl    string  `json:"cover_url"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Unit        string  `json:"unit"`
}

type ProductListRequest struct {
	StarId   *string `json:"star_id,optional"`
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type ProductSize struct {
	SizeName string `json:"size_name"`
	InStock  int64  `json:"in_stock"`
}

type RecommendStarListItem struct {
	StarId     string `json:"star_id"`
	StarAvatar string `json:"star_avatar"`
	StarName   string `json:"star_name"`
}

type RecommendStarListRequest struct {
}

type RecommendStarListResponse struct {
	Recommends []RecommendStarListItem `json:"recommends"`
}

type RemoveProductFromCartRequest struct {
	ProductId string `json:"product_id"`
	Color     string `json:"color"`
}

type RemoveProductFromCartResponse struct {
}

type SendForgetPasswordCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendForgetPasswordCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SendSignupCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
}

type SendSignupCaptchaResponse struct {
	CreatedAt int64 `json:"created_at"`
}

type SigninRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SigninResponse struct {
	UserId      string `json:"user_id"`
	Username    string `json:"name"`
	AccessToken string `json:"access_token"`
	Role        int64  `json:"role"`
	AvatarUrl   string `json:"avatar_url"`
}

type SignupRequest struct {
	Email       *string `json:"email,optional"`
	Phonenumber *string `json:"phone_number,optional"`
	Password    string  `json:"password"`
}

type SignupResponse struct {
	UserId string `json:"user_id"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	CoverUrl string `json:"cover_url"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}

type UserDetailRequest struct {
}

type UserDetailResponse struct {
	Id          string  `json:"id"`
	Phonenumber *string `json:"phone_number"`
	Email       *string `json:"email"`
	Username    string  `json:"username"`
}

type VerifyCaptchaRequest struct {
	Phonenumber *string `json:"phone_number,optional"`
	Email       *string `json:"email,optional"`
	Captcha     string  `json:"captcha"`
}

type VerifyCaptchaResponse struct {
	OK bool `json:"ok"`
}
