// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: star.proto

package star

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StarListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword  *string `protobuf:"bytes,1,opt,name=Keyword,proto3,oneof" json:"Keyword,omitempty"`
	Page     int64   `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize int64   `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *StarListRequest) Reset() {
	*x = StarListRequest{}
	mi := &file_star_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarListRequest) ProtoMessage() {}

func (x *StarListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarListRequest.ProtoReflect.Descriptor instead.
func (*StarListRequest) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{0}
}

func (x *StarListRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *StarListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StarListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type StarListResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// for star list
	CoverUrl string `protobuf:"bytes,3,opt,name=CoverUrl,proto3" json:"CoverUrl,omitempty"`
	// for recommend
	AvatarUrl string `protobuf:"bytes,4,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
}

func (x *StarListResponseItem) Reset() {
	*x = StarListResponseItem{}
	mi := &file_star_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarListResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarListResponseItem) ProtoMessage() {}

func (x *StarListResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarListResponseItem.ProtoReflect.Descriptor instead.
func (*StarListResponseItem) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{1}
}

func (x *StarListResponseItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StarListResponseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarListResponseItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *StarListResponseItem) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type StarListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stars []*StarListResponseItem `protobuf:"bytes,1,rep,name=Stars,proto3" json:"Stars,omitempty"`
	Total int64                   `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *StarListResponse) Reset() {
	*x = StarListResponse{}
	mi := &file_star_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarListResponse) ProtoMessage() {}

func (x *StarListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarListResponse.ProtoReflect.Descriptor instead.
func (*StarListResponse) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{2}
}

func (x *StarListResponse) GetStars() []*StarListResponseItem {
	if x != nil {
		return x.Stars
	}
	return nil
}

func (x *StarListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StarDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *StarDetailRequest) Reset() {
	*x = StarDetailRequest{}
	mi := &file_star_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarDetailRequest) ProtoMessage() {}

func (x *StarDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarDetailRequest.ProtoReflect.Descriptor instead.
func (*StarDetailRequest) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{3}
}

func (x *StarDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StarDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CoverUrl    string `protobuf:"bytes,4,opt,name=CoverUrl,proto3" json:"CoverUrl,omitempty"`
	AvatarUrl   string `protobuf:"bytes,5,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	PosterUrl   string `protobuf:"bytes,6,opt,name=PosterUrl,proto3" json:"PosterUrl,omitempty"`
}

func (x *StarDetailResponse) Reset() {
	*x = StarDetailResponse{}
	mi := &file_star_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarDetailResponse) ProtoMessage() {}

func (x *StarDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_star_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarDetailResponse.ProtoReflect.Descriptor instead.
func (*StarDetailResponse) Descriptor() ([]byte, []int) {
	return file_star_proto_rawDescGZIP(), []int{4}
}

func (x *StarDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StarDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StarDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StarDetailResponse) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *StarDetailResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *StarDetailResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

var File_star_proto protoreflect.FileDescriptor

var file_star_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70,
	0x63, 0x22, 0x6c, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x74, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x59, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x23, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0xb2, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x32, 0x7e, 0x0a, 0x04, 0x53, 0x74,
	0x61, 0x72, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x73, 0x74, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_star_proto_rawDescOnce sync.Once
	file_star_proto_rawDescData = file_star_proto_rawDesc
)

func file_star_proto_rawDescGZIP() []byte {
	file_star_proto_rawDescOnce.Do(func() {
		file_star_proto_rawDescData = protoimpl.X.CompressGZIP(file_star_proto_rawDescData)
	})
	return file_star_proto_rawDescData
}

var file_star_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_star_proto_goTypes = []any{
	(*StarListRequest)(nil),      // 0: rpc.StarListRequest
	(*StarListResponseItem)(nil), // 1: rpc.StarListResponseItem
	(*StarListResponse)(nil),     // 2: rpc.StarListResponse
	(*StarDetailRequest)(nil),    // 3: rpc.StarDetailRequest
	(*StarDetailResponse)(nil),   // 4: rpc.StarDetailResponse
}
var file_star_proto_depIdxs = []int32{
	1, // 0: rpc.StarListResponse.Stars:type_name -> rpc.StarListResponseItem
	0, // 1: rpc.Star.StarList:input_type -> rpc.StarListRequest
	3, // 2: rpc.Star.StarDetail:input_type -> rpc.StarDetailRequest
	2, // 3: rpc.Star.StarList:output_type -> rpc.StarListResponse
	4, // 4: rpc.Star.StarDetail:output_type -> rpc.StarDetailResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_star_proto_init() }
func file_star_proto_init() {
	if File_star_proto != nil {
		return
	}
	file_star_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_star_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_star_proto_goTypes,
		DependencyIndexes: file_star_proto_depIdxs,
		MessageInfos:      file_star_proto_msgTypes,
	}.Build()
	File_star_proto = out.File
	file_star_proto_rawDesc = nil
	file_star_proto_goTypes = nil
	file_star_proto_depIdxs = nil
}
