// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: staradmin.proto

package starclient

import (
	"context"

	"ymir.com/app/star/admin/star"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateStarRequest  = star.CreateStarRequest
	CreateStarResponse = star.CreateStarResponse
	StarDetailRequest  = star.StarDetailRequest
	StarDetailResponse = star.StarDetailResponse
	StarListItem       = star.StarListItem
	StarListRequest    = star.StarListRequest
	StarListResponse   = star.StarListResponse
	UpdateStarReqeust  = star.UpdateStarReqeust
	UpdateStarResponse = star.UpdateStarResponse

	Star interface {
		StarList(ctx context.Context, in *StarListRequest, opts ...grpc.CallOption) (*StarListResponse, error)
		StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error)
		UpdateStar(ctx context.Context, in *UpdateStarReqeust, opts ...grpc.CallOption) (*UpdateStarResponse, error)
		CreateStar(ctx context.Context, in *CreateStarRequest, opts ...grpc.CallOption) (*CreateStarResponse, error)
	}

	defaultStar struct {
		cli zrpc.Client
	}
)

func NewStar(cli zrpc.Client) Star {
	return &defaultStar{
		cli: cli,
	}
}

func (m *defaultStar) StarList(ctx context.Context, in *StarListRequest, opts ...grpc.CallOption) (*StarListResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.StarList(ctx, in, opts...)
}

func (m *defaultStar) StarDetail(ctx context.Context, in *StarDetailRequest, opts ...grpc.CallOption) (*StarDetailResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.StarDetail(ctx, in, opts...)
}

func (m *defaultStar) UpdateStar(ctx context.Context, in *UpdateStarReqeust, opts ...grpc.CallOption) (*UpdateStarResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.UpdateStar(ctx, in, opts...)
}

func (m *defaultStar) CreateStar(ctx context.Context, in *CreateStarRequest, opts ...grpc.CallOption) (*CreateStarResponse, error) {
	client := star.NewStarClient(m.cli.Conn())
	return client.CreateStar(ctx, in, opts...)
}
