// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: productadmin.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StarId *int64 `protobuf:"varint,1,opt,name=StarId,proto3,oneof" json:"StarId,omitempty"`
}

func (x *ProductCountRequest) Reset() {
	*x = ProductCountRequest{}
	mi := &file_productadmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCountRequest) ProtoMessage() {}

func (x *ProductCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productadmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCountRequest.ProtoReflect.Descriptor instead.
func (*ProductCountRequest) Descriptor() ([]byte, []int) {
	return file_productadmin_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCountRequest) GetStarId() int64 {
	if x != nil && x.StarId != nil {
		return *x.StarId
	}
	return 0
}

type ProductCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *ProductCountResponse) Reset() {
	*x = ProductCountResponse{}
	mi := &file_productadmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCountResponse) ProtoMessage() {}

func (x *ProductCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productadmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCountResponse.ProtoReflect.Descriptor instead.
func (*ProductCountResponse) Descriptor() ([]byte, []int) {
	return file_productadmin_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_productadmin_proto protoreflect.FileDescriptor

var file_productadmin_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x3d, 0x0a, 0x13, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x53, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x52, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x12, 0x47, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_productadmin_proto_rawDescOnce sync.Once
	file_productadmin_proto_rawDescData = file_productadmin_proto_rawDesc
)

func file_productadmin_proto_rawDescGZIP() []byte {
	file_productadmin_proto_rawDescOnce.Do(func() {
		file_productadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_productadmin_proto_rawDescData)
	})
	return file_productadmin_proto_rawDescData
}

var file_productadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_productadmin_proto_goTypes = []any{
	(*ProductCountRequest)(nil),  // 0: admin.ProductCountRequest
	(*ProductCountResponse)(nil), // 1: admin.ProductCountResponse
}
var file_productadmin_proto_depIdxs = []int32{
	0, // 0: admin.Product.ProductCount:input_type -> admin.ProductCountRequest
	1, // 1: admin.Product.ProductCount:output_type -> admin.ProductCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_productadmin_proto_init() }
func file_productadmin_proto_init() {
	if File_productadmin_proto != nil {
		return
	}
	file_productadmin_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_productadmin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_productadmin_proto_goTypes,
		DependencyIndexes: file_productadmin_proto_depIdxs,
		MessageInfos:      file_productadmin_proto_msgTypes,
	}.Build()
	File_productadmin_proto = out.File
	file_productadmin_proto_rawDesc = nil
	file_productadmin_proto_goTypes = nil
	file_productadmin_proto_depIdxs = nil
}
