// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateProductRequest struct {
	StarId      string         `json:"star_id"`
	Description string         `json:"description"`
	Name        string         `json:"name"`
	Detail      *string        `json:"detail,optional"`
	Color       []ProductColor `json:"color"`
}

type CreateProductResponse struct {
	ProductId string `json:"product_id"`
}

type CreateStarResponse struct {
	StarId string `json:"star_id"`
}

type CreteStarRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,optional"`
	CoverUrl    string  `json:"cover_url"`
	AvatarUrl   string  `json:"avatar_url"`
	PosterUrl   string  `json:"poster_url"`
}

type DeleteProductRequest struct {
	ProductId string `path:"productId"`
}

type DeleteProductResponse struct {
	ProductId string `json:"product_id"`
}

type ProductColor struct {
	ColorName       string             `json:"color_name"`
	CoverUrl        string             `json:"cover_url"`
	ImagesUrl       string             `json:"images_url"`
	DetailImagesUrl string             `json:"detail_images_url"`
	Price           int64              `json:"price"`
	Unit            string             `json:"unit"`
	Sizes           []ProductColorSize `json:"sizes"`
	IsDefault       bool               `json:"is_default"`
}

type ProductColorSize struct {
	Size    string `json:"size"`
	InStock int64  `json:"in_stock"`
}

type ProductListColorItem struct {
	CoverUrl string `json:"cover_url"`
	Price    int64  `json:"price"`
	Unit     string `json:"unit"`
}

type ProductListItem struct {
	Id           string               `json:"id"`
	Description  string               `json:"description"`
	Name         string               `json:"name"`
	Rate         float64              `json:"rate"`
	RateCount    int64                `json:"rate_count"`
	SoldNum      int64                `json:"sold_num"`
	DefaultColor ProductListColorItem `json:"default_color"`
}

type ProductListRequest struct {
	StarId   *string `json:"star_id,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type SigninRequest struct {
	Phonenumber string `json:"phone_number"`
	Captcha     string `json:"captcha"`
}

type SigninResponse struct {
	UserId      string `json:"user_id"`
	Name        string `json:"name"`
	Phonenumber string `json:"phonenumber"`
	AccessToken string `json:"access_token"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Rate        string              `json:"rate"`
	RateCount   int64               `json:"rate_count"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id           string  `json:"id"`
	Name         string  `json:"name"`
	CreatedAt    int64   `json:"created_at"`
	AvatarUrl    string  `json:"avatar_url"`
	Description  string  `json:"description"`
	ProductTotal int64   `json:"product_total"`
	Rate         float64 `json:"rate"`
	RateCount    int64   `json:"rate_count"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}

type UpdateStarRequest struct {
	StarId      string  `json:"star_id"`
	Name        *string `json:"name,optional"`
	Description *string `json:"description,optional"`
	CoverUrl    *string `json:"cover_url,optional"`
	AvatarUrl   *string `json:"avatar_url,optional"`
	PosterUrl   *string `json:"poster_url,optional"`
}

type UpdateStarResponse struct {
	StarId string `json:"star_id"`
}
