// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateStarResponse struct {
	StarId string `json:"star_id"`
}

type CreteStarRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,optional"`
	CoverUrl    string  `json:"cover_url"`
	AvatarUrl   string  `json:"avatar_url"`
	PosterUrl   string  `json:"poster_url"`
}

type ProductListItem struct {
	Id          string  `json:"id"`
	CoverUrl    string  `json:"cover_url"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Unit        string  `json:"unit"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type SigninRequest struct {
	Phonenumber string `json:"phone_number"`
	Captcha     string `json:"captcha"`
}

type SigninResponse struct {
	UserId      string `json:"user_id"`
	Name        string `json:"name"`
	Phonenumber string `json:"phonenumber"`
	AccessToken string `json:"access_token"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Rate        string              `json:"rate"`
	RateCount   int64               `json:"rate_count"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id           string  `json:"id"`
	Name         string  `json:"name"`
	AvatarUrl    string  `json:"avatar_url"`
	Description  string  `json:"description"`
	ProductTotal int64   `json:"product_total"`
	Rate         float64 `json:"rate"`
	RateCount    int64   `json:"rate_count"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}

type UpdateStarRequest struct {
	StarId      string  `json:"star_id"`
	Name        *string `json:"name,optional"`
	Description *string `json:"description,optional"`
	CoverUrl    *string `json:"cover_url,optional"`
	AvatarUrl   *string `json:"avatar_url,optional"`
	PosterUrl   *string `json:"poster_url,optional"`
}

type UpdateStarResponse struct {
	StarId string `json:"star_id"`
}
