// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ProductListItem struct {
	Id          string  `json:"id"`
	CoverUrl    string  `json:"cover_url"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Unit        string  `json:"unit"`
}

type ProductListResponse struct {
	Total    int64             `json:"total"`
	Products []ProductListItem `json:"products"`
}

type StarDetailRequest struct {
	Id string `path:"id"`
}

type StarDetailResponse struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Rate        string              `json:"rate"`
	RateCount   int64               `json:"rate_count"`
	CoverUrl    string              `json:"cover_url"`
	AvatarUrl   string              `json:"avatar_url"`
	PosterUrl   string              `json:"poster_url"`
	Products    ProductListResponse `json:"products"`
}

type StarListItem struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	CoverUrl string `json:"cover_url"`
}

type StarListRequest struct {
	Keyword  *string `json:"keyword,optional"`
	Page     int64   `json:"page"`
	PageSize int64   `json:"page_size"`
}

type StarListResponse struct {
	ToTal int64          `json:"total"`
	Stars []StarListItem `json:"stars"`
}
