// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_GetUserInfo_FullMethodName              = "/user.user/GetUserInfo"
	User_GetUserLocal_FullMethodName             = "/user.user/GetUserLocal"
	User_GetUserGoogle_FullMethodName            = "/user.user/GetUserGoogle"
	User_SendCaptchaToEmail_FullMethodName       = "/user.user/SendCaptchaToEmail"
	User_SendCaptchaToPhonenumber_FullMethodName = "/user.user/SendCaptchaToPhonenumber"
	User_GetCaptchaByEmail_FullMethodName        = "/user.user/GetCaptchaByEmail"
	User_GetCaptchaByPhonenumber_FullMethodName  = "/user.user/GetCaptchaByPhonenumber"
	User_DeleteCaptcha_FullMethodName            = "/user.user/DeleteCaptcha"
	User_WriteUserLocalInDB_FullMethodName       = "/user.user/WriteUserLocalInDB"
	User_WriteUserGoogleInDB_FullMethodName      = "/user.user/WriteUserGoogleInDB"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	GetUserLocal(ctx context.Context, in *GetUserLocalRequest, opts ...grpc.CallOption) (*GetUserLocalResponse, error)
	GetUserGoogle(ctx context.Context, in *GetUserGoogleRequest, opts ...grpc.CallOption) (*GetUserGoogleResponse, error)
	SendCaptchaToEmail(ctx context.Context, in *SendCaptchaToEmailRequest, opts ...grpc.CallOption) (*SendCaptchaToEmailResponse, error)
	SendCaptchaToPhonenumber(ctx context.Context, in *SendCaptchaToPhonenumberRequest, opts ...grpc.CallOption) (*SendCaptchaToPhonenumberResponse, error)
	GetCaptchaByEmail(ctx context.Context, in *GetCaptchaByEmailRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error)
	GetCaptchaByPhonenumber(ctx context.Context, in *GetCaptchaByPhonenumberRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error)
	DeleteCaptcha(ctx context.Context, in *DeleteCaptchaRequest, opts ...grpc.CallOption) (*DeleteCaptchaResponse, error)
	WriteUserLocalInDB(ctx context.Context, in *WriteUserLocalRequest, opts ...grpc.CallOption) (*WriteUserLocalResponse, error)
	WriteUserGoogleInDB(ctx context.Context, in *WriteUserGoogleRequest, opts ...grpc.CallOption) (*WriteUserGoogleResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, User_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserLocal(ctx context.Context, in *GetUserLocalRequest, opts ...grpc.CallOption) (*GetUserLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLocalResponse)
	err := c.cc.Invoke(ctx, User_GetUserLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserGoogle(ctx context.Context, in *GetUserGoogleRequest, opts ...grpc.CallOption) (*GetUserGoogleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGoogleResponse)
	err := c.cc.Invoke(ctx, User_GetUserGoogle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SendCaptchaToEmail(ctx context.Context, in *SendCaptchaToEmailRequest, opts ...grpc.CallOption) (*SendCaptchaToEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCaptchaToEmailResponse)
	err := c.cc.Invoke(ctx, User_SendCaptchaToEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SendCaptchaToPhonenumber(ctx context.Context, in *SendCaptchaToPhonenumberRequest, opts ...grpc.CallOption) (*SendCaptchaToPhonenumberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCaptchaToPhonenumberResponse)
	err := c.cc.Invoke(ctx, User_SendCaptchaToPhonenumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCaptchaByEmail(ctx context.Context, in *GetCaptchaByEmailRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptchaResponse)
	err := c.cc.Invoke(ctx, User_GetCaptchaByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCaptchaByPhonenumber(ctx context.Context, in *GetCaptchaByPhonenumberRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptchaResponse)
	err := c.cc.Invoke(ctx, User_GetCaptchaByPhonenumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteCaptcha(ctx context.Context, in *DeleteCaptchaRequest, opts ...grpc.CallOption) (*DeleteCaptchaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCaptchaResponse)
	err := c.cc.Invoke(ctx, User_DeleteCaptcha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) WriteUserLocalInDB(ctx context.Context, in *WriteUserLocalRequest, opts ...grpc.CallOption) (*WriteUserLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteUserLocalResponse)
	err := c.cc.Invoke(ctx, User_WriteUserLocalInDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) WriteUserGoogleInDB(ctx context.Context, in *WriteUserGoogleRequest, opts ...grpc.CallOption) (*WriteUserGoogleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteUserGoogleResponse)
	err := c.cc.Invoke(ctx, User_WriteUserGoogleInDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	GetUserLocal(context.Context, *GetUserLocalRequest) (*GetUserLocalResponse, error)
	GetUserGoogle(context.Context, *GetUserGoogleRequest) (*GetUserGoogleResponse, error)
	SendCaptchaToEmail(context.Context, *SendCaptchaToEmailRequest) (*SendCaptchaToEmailResponse, error)
	SendCaptchaToPhonenumber(context.Context, *SendCaptchaToPhonenumberRequest) (*SendCaptchaToPhonenumberResponse, error)
	GetCaptchaByEmail(context.Context, *GetCaptchaByEmailRequest) (*GetCaptchaResponse, error)
	GetCaptchaByPhonenumber(context.Context, *GetCaptchaByPhonenumberRequest) (*GetCaptchaResponse, error)
	DeleteCaptcha(context.Context, *DeleteCaptchaRequest) (*DeleteCaptchaResponse, error)
	WriteUserLocalInDB(context.Context, *WriteUserLocalRequest) (*WriteUserLocalResponse, error)
	WriteUserGoogleInDB(context.Context, *WriteUserGoogleRequest) (*WriteUserGoogleResponse, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServer) GetUserLocal(context.Context, *GetUserLocalRequest) (*GetUserLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLocal not implemented")
}
func (UnimplementedUserServer) GetUserGoogle(context.Context, *GetUserGoogleRequest) (*GetUserGoogleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserGoogle not implemented")
}
func (UnimplementedUserServer) SendCaptchaToEmail(context.Context, *SendCaptchaToEmailRequest) (*SendCaptchaToEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCaptchaToEmail not implemented")
}
func (UnimplementedUserServer) SendCaptchaToPhonenumber(context.Context, *SendCaptchaToPhonenumberRequest) (*SendCaptchaToPhonenumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCaptchaToPhonenumber not implemented")
}
func (UnimplementedUserServer) GetCaptchaByEmail(context.Context, *GetCaptchaByEmailRequest) (*GetCaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptchaByEmail not implemented")
}
func (UnimplementedUserServer) GetCaptchaByPhonenumber(context.Context, *GetCaptchaByPhonenumberRequest) (*GetCaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptchaByPhonenumber not implemented")
}
func (UnimplementedUserServer) DeleteCaptcha(context.Context, *DeleteCaptchaRequest) (*DeleteCaptchaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCaptcha not implemented")
}
func (UnimplementedUserServer) WriteUserLocalInDB(context.Context, *WriteUserLocalRequest) (*WriteUserLocalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteUserLocalInDB not implemented")
}
func (UnimplementedUserServer) WriteUserGoogleInDB(context.Context, *WriteUserGoogleRequest) (*WriteUserGoogleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteUserGoogleInDB not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call pancis, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserLocal(ctx, req.(*GetUserLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserGoogle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserGoogle(ctx, req.(*GetUserGoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SendCaptchaToEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCaptchaToEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SendCaptchaToEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SendCaptchaToEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SendCaptchaToEmail(ctx, req.(*SendCaptchaToEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SendCaptchaToPhonenumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCaptchaToPhonenumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SendCaptchaToPhonenumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SendCaptchaToPhonenumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SendCaptchaToPhonenumber(ctx, req.(*SendCaptchaToPhonenumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCaptchaByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptchaByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCaptchaByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCaptchaByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCaptchaByEmail(ctx, req.(*GetCaptchaByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCaptchaByPhonenumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptchaByPhonenumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCaptchaByPhonenumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCaptchaByPhonenumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCaptchaByPhonenumber(ctx, req.(*GetCaptchaByPhonenumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCaptchaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteCaptcha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteCaptcha(ctx, req.(*DeleteCaptchaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_WriteUserLocalInDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteUserLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WriteUserLocalInDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WriteUserLocalInDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WriteUserLocalInDB(ctx, req.(*WriteUserLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_WriteUserGoogleInDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteUserGoogleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).WriteUserGoogleInDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_WriteUserGoogleInDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).WriteUserGoogleInDB(ctx, req.(*WriteUserGoogleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserLocal",
			Handler:    _User_GetUserLocal_Handler,
		},
		{
			MethodName: "GetUserGoogle",
			Handler:    _User_GetUserGoogle_Handler,
		},
		{
			MethodName: "SendCaptchaToEmail",
			Handler:    _User_SendCaptchaToEmail_Handler,
		},
		{
			MethodName: "SendCaptchaToPhonenumber",
			Handler:    _User_SendCaptchaToPhonenumber_Handler,
		},
		{
			MethodName: "GetCaptchaByEmail",
			Handler:    _User_GetCaptchaByEmail_Handler,
		},
		{
			MethodName: "GetCaptchaByPhonenumber",
			Handler:    _User_GetCaptchaByPhonenumber_Handler,
		},
		{
			MethodName: "DeleteCaptcha",
			Handler:    _User_DeleteCaptcha_Handler,
		},
		{
			MethodName: "WriteUserLocalInDB",
			Handler:    _User_WriteUserLocalInDB_Handler,
		},
		{
			MethodName: "WriteUserGoogleInDB",
			Handler:    _User_WriteUserGoogleInDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
