// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: order.proto

package orderclient

import (
	"context"

	"ymir.com/app/order/rpc/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderRequest      = order.CreateOrderRequest
	CreateOrderResponse     = order.CreateOrderResponse
	GetOrderRequest         = order.GetOrderRequest
	GetOrderResponse        = order.GetOrderResponse
	OrderItem               = order.OrderItem
	SoftDeleteOrderRequest  = order.SoftDeleteOrderRequest
	SoftDeleteOrderResponse = order.SoftDeleteOrderResponse

	Order interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		CreateOrderRollback(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		SoftDeleteOrder(ctx context.Context, in *SoftDeleteOrderRequest, opts ...grpc.CallOption) (*SoftDeleteOrderResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) CreateOrderRollback(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrderRollback(ctx, in, opts...)
}

func (m *defaultOrder) SoftDeleteOrder(ctx context.Context, in *SoftDeleteOrderRequest, opts ...grpc.CallOption) (*SoftDeleteOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.SoftDeleteOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}
