// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: organizer.proto

package organizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Organizer_GetOrganizer_FullMethodName = "/organizer.organizer/GetOrganizer"
)

// OrganizerClient is the client API for Organizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrganizerClient interface {
	GetOrganizer(ctx context.Context, in *GetOrganizerRequest, opts ...grpc.CallOption) (*GetorganizerResponse, error)
}

type organizerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizerClient(cc grpc.ClientConnInterface) OrganizerClient {
	return &organizerClient{cc}
}

func (c *organizerClient) GetOrganizer(ctx context.Context, in *GetOrganizerRequest, opts ...grpc.CallOption) (*GetorganizerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetorganizerResponse)
	err := c.cc.Invoke(ctx, Organizer_GetOrganizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizerServer is the server API for Organizer service.
// All implementations must embed UnimplementedOrganizerServer
// for forward compatibility.
type OrganizerServer interface {
	GetOrganizer(context.Context, *GetOrganizerRequest) (*GetorganizerResponse, error)
	mustEmbedUnimplementedOrganizerServer()
}

// UnimplementedOrganizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizerServer struct{}

func (UnimplementedOrganizerServer) GetOrganizer(context.Context, *GetOrganizerRequest) (*GetorganizerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizer not implemented")
}
func (UnimplementedOrganizerServer) mustEmbedUnimplementedOrganizerServer() {}
func (UnimplementedOrganizerServer) testEmbeddedByValue()                   {}

// UnsafeOrganizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizerServer will
// result in compilation errors.
type UnsafeOrganizerServer interface {
	mustEmbedUnimplementedOrganizerServer()
}

func RegisterOrganizerServer(s grpc.ServiceRegistrar, srv OrganizerServer) {
	// If the following call pancis, it indicates UnimplementedOrganizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Organizer_ServiceDesc, srv)
}

func _Organizer_GetOrganizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizerServer).GetOrganizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizer_GetOrganizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizerServer).GetOrganizer(ctx, req.(*GetOrganizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Organizer_ServiceDesc is the grpc.ServiceDesc for Organizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Organizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "organizer.organizer",
	HandlerType: (*OrganizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrganizer",
			Handler:    _Organizer_GetOrganizer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organizer.proto",
}
