// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: order.proto

package server

import (
	"context"

	"ymir.com/app/order/rpc/internal/logic"
	"ymir.com/app/order/rpc/internal/svc"
	"ymir.com/app/order/rpc/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) CreateOrderRollback(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderRollbackLogic(ctx, s.svcCtx)
	return l.CreateOrderRollback(in)
}

func (s *OrderServer) SoftDeleteOrder(ctx context.Context, in *order.SoftDeleteOrderRequest) (*order.SoftDeleteOrderResponse, error) {
	l := logic.NewSoftDeleteOrderLogic(ctx, s.svcCtx)
	return l.SoftDeleteOrder(in)
}

func (s *OrderServer) GetOrder(ctx context.Context, in *order.GetOrderRequest) (*order.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
