Name: ymir.product.admin.rpc
ListenOn: 0.0.0.0:3003
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: ymir.product.admin.rpc

DataSource: root:test123@tcp(localhost:3306)/ymir?parseTime=true&loc=UTC
CacheRedis:
  - Host: localhost:6379

BizRedis:
  Host: 127.0.0.1:6379

Log:
  ServiceName: ymir.star.admin.rpc
  Level: debug