// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: organizer.proto

package server

import (
	"context"

	"ymir.com/app/organizer/rpc/internal/logic"
	"ymir.com/app/organizer/rpc/internal/svc"
	"ymir.com/app/organizer/rpc/organizer"
)

type OrganizerServer struct {
	svcCtx *svc.ServiceContext
	organizer.UnimplementedOrganizerServer
}

func NewOrganizerServer(svcCtx *svc.ServiceContext) *OrganizerServer {
	return &OrganizerServer{
		svcCtx: svcCtx,
	}
}

func (s *OrganizerServer) GetOrganizer(ctx context.Context, in *organizer.GetOrganizerRequest) (*organizer.GetorganizerResponse, error) {
	l := logic.NewGetOrganizerLogic(ctx, s.svcCtx)
	return l.GetOrganizer(in)
}
