Name: ymir.product.rpc
ListenOn: 0.0.0.0:8002
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: ymir.product.rpc

DataSource: root:test123@tcp(localhost:3306)/ymir?parseTime=true&loc=UTC
CacheRedis:
  - Host: localhost:6379
BizRedis:
  Host: 127.0.0.1:6379

Log:
  ServiceName: ymir.product.rpc
  Level: error
  Mode: file
  Path: /home/ecs-user/log/rpc/product
  Stat: true
  KeepDays: 7

Mode: pro